lib/live_view_stripe_web/router.ex
defmodule LiveViewStripeWeb.Router do
  use LiveViewStripeWeb, :router

  import LiveViewStripeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LiveViewStripeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/webhooks", LiveViewStripeWeb do
    pipe_through :api
    post "/stripe", StripeWebhookController, :create
  end

  scope "/", LiveViewStripeWeb.SubscribersLive do
    pipe_through [:browser, :require_active_subscription]
    live "/home", Home, :index
  end

  scope "/", LiveViewStripeWeb.SubscriptionLive do
    pipe_through [:browser, :require_authenticated_user]
    live "/subscriptions/new", New, :new
  end

  scope "/", LiveViewStripeWeb.PricingLive do
    pipe_through [:browser]
    live "/", Page, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", LiveViewStripeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: LiveViewStripeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", LiveViewStripeWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", LiveViewStripeWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", LiveViewStripeWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/live_view_stripe_web/controllers/user_session_controller.ex
defmodule LiveViewStripeWeb.UserSessionController do
  use LiveViewStripeWeb, :controller

  alias LiveViewStripe.Accounts
  alias LiveViewStripeWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/live_view_stripe_web/views/user_session_view.ex
defmodule LiveViewStripeWeb.UserSessionView do
  use LiveViewStripeWeb, :view
end

lib/live_view_stripe_web/templates/user_session/new.html.heex
<section>
  <div class="bg-gray-100 p-5 pt-10 mt-5 max-w-md mx-auto text-left">
    <h1 class="text-4xl font-bold leading-tight text-gray-900 md:text-5xl md:font-extrabold">Login</h1>
    <hr class="mt-5 mb-5" />
        <div class="mx-auto mt-5 mb-2 max-w-sm">
            <div class="justify-between p-2 text-center">
              <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
                <%= if @error_message do %>
                  <div class="alert alert-danger">
                    <p><%= @error_message %></p>
                  </div>
                <% end %>
                <div class="text-left mb-3">
                  <%= label f, :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
                  <%= email_input f, :email, required: true,
                        class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
                  <%= error_tag f, :email %>
                </div>
                <div class="text-left mb-5">
                  <%= label f, :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
                  <%= password_input f, :password, required: true,
                        class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
                  <%= error_tag f, :password %>
                </div>
                <div class="text-left mb-5">
                  <%= checkbox f, :remember_me %>
                  <%= label f, :remember_me, "Keep me logged in for 60 days",
                        class: "text-gray-700 text-sm font-bold mb-2" %>
                </div>
                <div class="text-left">
                  <%= submit "Login",
                        class: "bg-red-500 hover:bg-red-700 text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
                </div>
              </.form>
              <hr class="mt-5 mb-5" />
              <p class="text-red-500">
                <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "text-red-500" %> |
                <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-red-500" %>
              </p>
            </div>
        </div>
    </div>
</section>